<?php

namespace AppBundle\Repository;

/**
 * BooklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooklistRepository extends \Doctrine\ORM\EntityRepository
{
}
